apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::401869011795:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1RPNHCEP5SAVV
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::401869011795:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2023-07-13T05:18:44Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1017"
  uid: fedf7ddc-c019-4225-884d-4b09e52b2c06
